### ISSUE TITLE
2.5.x compatibility

### ISSUE THREAD

**Issue by atopcu** [nanego/redmine_datetime_custom_field#1]
I need this for redmine 2.5.2
Regards

**Comment by nanego** [comment]
You can try to comment this line in the init.rb file:

    requires_redmine :version_or_higher => '2.6.0'
and carefully test that everything is working.

That would be great if I could get some feedback and make this plugin available for older Redmine versions.

**Comment by atopcu** [comment]
Thanks nanego! today I'm using this on rm 3.1
