### ISSUE TITLE
bad sorting date 

### ISSUE THREAD

**Issue by lba31** [nanego/redmine_datetime_custom_field#11]
Hi,
in issue's list, sorting by created or updated date is ok, but sorting by date custom field is not.
Examples : 
Sorting by created date :
![image](https://user-images.githubusercontent.com/47324971/52214440-ec386a80-2891-11e9-88b4-96ac427f8ab5.png)
Sorting by updated date : 
![image](https://user-images.githubusercontent.com/47324971/52214160-4b49af80-2891-11e9-9f9e-2b339ae9ccc6.png)
Sorting by custom fiel date (Depart) :
![image](https://user-images.githubusercontent.com/47324971/52214238-77fdc700-2891-11e9-817b-162f9bbdd3f3.png)
As you can see, in 3rd screen, the 4th and 5th line are not correctly sorted.

I make a try in french translation : not ok ; and in english : not ok.
Can you issued this ?
Thanks

**Comment by nanego** [comment]
Hi. Thanks for reporting the issue.
I have just fixed it. Please upgrade to the last version of the plugin.
