### ISSUE TITLE
Using this as start/due date?

### ISSUE THREAD

**Issue by pmcculey** [nanego/redmine_datetime_custom_field#14]
I'd like to use this as the start/due date (with time) such that it shows up on the correct day(s) on both Gantt and calendar. Is this possible? Its not obvious to be, but I'm a very new redmine user.

Thanks for any info.

**Comment by nanego** [comment]
I hope I will have time to work on this feature soon.
We would like to use start and due dates with hours and minutes too.

**Comment by pmcculey** [comment]
Well that would be great. Thanks for considering it for inclusion. I'd be grateful for any updates. Seems like something that should already exist, but apparently not.

Joe

**Comment by nanego** [comment]
With the latest version of the plugin, you can now use start and due dates with hours.
This functionality must be activated  in the plugin settings.

Please feel free to test it and give feedback (and do not forget to run the migrations after updating the plugin with the `rails redmine:plugins` command).
