### ISSUE TITLE
Error To_Timestamp when we active order by

### ISSUE THREAD

**Issue by odurgeau** [nanego/redmine_datetime_custom_field#17]
Hello,

When I add the date column and I try to sort the column, I have the following error :  

```
Query::StatementInvalid: Mysql2::Error: FUNCTION redmine411.to_timestamp does not exist: SELECT ... ORDER BY to_timestamp(cf_3.value, 'DD/MM/YYYY HH24:MI') ASC, issues.id DESC LIMIT 100 OFFSET 0
```

If I modify this file `lib/redmine_datetime_custom_field/field_format_patch.rb` and this line

```
Arel.sql "to_timestamp(#{join_alias custom_field}.value, 'DD/MM/YYYY HH24:MI')"
```

by 

```
Arel.sql "STR_TO_DATE(#{join_alias custom_field}.value, '%d/%m/%Y %k:%i')"
```

It works !

**Comment by lormico** [comment]
I'm encountering the same issue while using MariaDB (open alternative to MySQL) as a DB back-end. 
The function `to_timestamp` is not available on MySQL-compatible DBs, which are officially supported by Redmine; the _order by_ clause should be corrected in this case to use the `str_to_date` function.

I'll see if I can code the fix and propose a pull request.

**Comment by nanego** [comment]
I've just updated the plugin. Can you try the latest version and confirm it works now?

**Comment by lormico** [comment]
Unfortunately it won't work:
```
NoMethodError (undefined method `connection' for Redmine::FieldFormat::DateFormat:Class
Did you mean?  concerning):
  
plugins/redmine_datetime_custom_field/lib/redmine_datetime_custom_field/field_format_patch.rb:39:in `order_statement'
```

**Comment by nanego** [comment]
Now it should work.

**Comment by lormico** [comment]
Nice work!

Just to note: the `str_to_date` function is not available on Microsoft SQL Server, which is another officially supported DB back-end: I would suggest to edit the lines
https://github.com/nanego/redmine_datetime_custom_field/blob/d65dc1c017a0e3030353cc755a63bb61e10904be/lib/redmine_datetime_custom_field/field_format_patch.rb#L39-L43
into
```ruby
          if custom_field.class.connection.adapter_name.downcase.to_sym == :mysql2
            Arel.sql "STR_TO_DATE(#{join_alias custom_field}.value, '%d/%m/%Y %H:%i')"
          else
            Arel.sql "to_timestamp(#{join_alias custom_field}.value, 'DD/MM/YYYY HH24:MI')"
          end
```

**Comment by nanego** [comment]
I didn't know the to_timestamp method was compatible with SQL Server. I will adapt the code.
