### ISSUE TITLE
Select2 functionality is hidden/dormant and shows up unexpectedly when Select2 script is made available

### ISSUE THREAD

**Issue by lormico** [nanego/redmine_datetime_custom_field#21]
https://github.com/nanego/redmine_datetime_custom_field/blob/36d522d305c8e8361a2c0241e5edc88653efb3db/assets/javascripts/datetime_custom_field.js#L54-L63

Since Select2 is never imported by the plugin, the function `addSelect2ToSelectTags` will never enable the widget as intended.

As soon as Select2's distribution is made available (by another plugin, for instance), this unadvertised functionality will show up, and there is no way to disable it.

Since this functionality's main (only?) effect is to enable Select2 on all filters' `select` boxes, I personally _don't feel it is something that belongs in the scope of this plugin_.

As such, I would suggest either:
- to move the functionality to another plugin, importing Select2 as needed
- to add a plugin setting to enable or disable the `addSelect2ToSelectTags` function

**Comment by nanego** [comment]
Hello. I think you are right. We should move this functionality to another plugin.

**Comment by nanego** [comment]
The select2 functionality has been removed from this plugin. Thank you for reporting the issue.
