### ISSUE TITLE
Update plugin for V.5

### ISSUE THREAD

**Issue by Daradaal** [nanego/redmine_datetime_custom_field#24]
Hello,

Is it possible to update the plugin version for redmine version 5.

Thanks in advance for your time! :)

**Comment by formigadiablo** [comment]
Any updates on this?

**Comment by whotopia** [comment]
in redmine_datetime_custom_field/init.rb

this should do it:

```
# Custom patches
#require_dependency 'redmine_datetime_custom_field/hooks'
require_dependency File.expand_path('lib/redmine_datetime_custom_field/hooks', __dir__)
```

There may be other 5.x compatibility issues, but this fixes the issue with the hooks.

**Comment by whotopia** [comment]
> Hello everyone, I wanted to inform you that I have made updates to the plugin, and it should now be fully compatible with both Redmine 5 and Redmine 4. Could you try out the latest version and provide confirmation that everything is functioning as it did before? Thank you

Seems to work, though error log shows the following, which I assume is informational in nature only?

`[2023-09-17T10:15:21.046130 #182198] ERROR -- : [fe6ea59c-aa5c-40a2-90d9-0fa61cbdda68] Deface: [ERROR] The original source for 'add_time_to_date_field' has changed, this override should be reviewed to ensure it's still valid.`

**Comment by nanego** [comment]
Thank you for the feedback. You can safely disregard the warning message.
