### ISSUE TITLE
Custom field Hour setting doesn't being saved

### ISSUE THREAD

**Issue by etonline** [nanego/redmine_datetime_custom_field#6]
Hello,

After I install this plugin, when I want to change "Hour" to "Yes" in custom date field, it shows "Successful update.", but "Hour" option is still "No".
If I enter default value with hour, along with "Hour" to "Yes" setting, error message prompt out after saving it.
![Screenshot](https://i.imgur.com/ZTqCOui.png)

Please find my environment below:

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_2fa                    1.3.2
  redmine_base_deface            0.0.1
  redmine_datetime_custom_field  3.3.0

**Comment by etonline** [comment]
It seems to be caused by not adding "show_hours" into "safe_attributes" for "custom_field" model.
I'm don't know how to do relevant overwrite so cannot provide any patch, hope this helps.

**Comment by nanego** [comment]
Thanks for reporting the issue. It has been fixed in the last commits.
