### ISSUE TITLE
Not compatible with redmine_dmsf

### ISSUE THREAD

**Issue by cuoilennaocacban** [nanego/redmine_datetime_custom_field#8]
DMSF is quite a popular plugin for redmine.

The issue is cause by calendar_for, since both plugin overwrite this method

[https://github.com/danmunn/redmine_dmsf](https://github.com/danmunn/redmine_dmsf)

**Comment by nanego** [comment]
Sorry I cannot ensure compatibility with all other plugins.
I don't know the redmine_dmsf plugin. But feel free to open a Pull Request if you know how to make them compatible.
