### ISSUE TITLE
how to install in redmine 3.3.1

### ISSUE THREAD

**Issue by sai5555** [nanego/redmine_datetime_custom_field#9]
Hi 
How to install into redmine 3.3.1
Thanks

I had try this but it is  still not install.
![2017-10-18_205208](https://user-images.githubusercontent.com/6488772/31719502-474ad640-b446-11e7-9112-0f8511c0d80a.png)

**Comment by nanego** [comment]
The plugin has been updated for latest Redmine version (3.4.x).
But you can use it with previous 3.3 version if you use a previous version: e6a59bcf16e222f0f68f4a579793a216195bdf6f
